### ISSUE TITLE
Content-type of source in p:hash is wrong

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#78] opened 2019-04-30 16:56 UTC
The source port is flagged as "any" but it has to be "XML HTML" given that the NODE where the hash is inserted is selected by a MATCH-PATTERN.

**Comment by xml-project** [comment] 2019-05-01 11:45
Reminder: If we make this change, the result port should also be "XML HTML" and not "application/xml".

**Comment by Conal-Tuohy** [comment] 2019-05-02 02:34
It would be nice to be able to insert a hash into JSON document as well (though some additional wording would be needed, at least, so that map values could be updated, as attribute values can).

**Comment by gimsieke** [comment] 2019-05-02 06:03
Maybe this can be achieved more naturally if the `p:hash` step were provided as a function `p:hash()` with the same signature(s), too? This we’d have to leave for a future spec update though.

There is also an EXPath [`crypto:hash()`](http://expath.org/spec/crypto/editor#hash-function) function but I doubt that the EXPath crypto module will be available by default in early XProc 3.0 implementations.

**Comment by Conal-Tuohy** [comment] 2019-05-02 08:26
There are a few steps whose functionality might be more accessible if provided as functions. For example using `p:add-attribute` and an XPath function `p:uuid` could replace the `p:uuid` step, and `p:www-form-urldecode` is similar (see https://github.com/xproc/3.0-steps/issues/22#issuecomment-268949002). Functions like `p:episode` could have been implemented as steps, too (i.e. with a `match` attribute). I wonder what principled criteria could be adduced for either approach (i.e. on what basis should we have a step in one case and a function in the other)?

**Comment by ndw** [comment] 2019-05-02 14:50
If I had to give an answer off the top of my head, I'd say "functions don't do node construction". On that basis, p:hash and p:uuid could be functions, p:add-attribute could not.

I have reservations about taking all of the steps that could be functions and turning them into functions, though. That's an awfully large language change pretty late in the process.

**Comment by Conal-Tuohy** [comment] 2019-05-03 03:33
BTW my mention of `p:add-attribute` was intended to imply that it was a generic step which could be used in combination with functions like `p:uuid()`, `p:episode()`, `p:hash()`, `p:www-form-urldecode()`, etc, to replace the specific steps `p:uuid`, `p:hash`, `p:www-form-urldecode`, and so on. But equally those functions could be very useful in other circumstances which don't involve node construction in a document: with `p:string-replace`, or `p:set-properties`, or as parameters to `p:xslt` or `p:xquery`, or just assigning to a variable. 

I don't think there are many such steps that would be candidates for turning into functions. Maybe just these ones?

- uuid
- hash
- www-form-urldecode
- www-form-urlencode

**Closed** 2019-05-16 15:28 UTC
